# Vision Linux pacman configuration

[options]
Architecture = x86_64
SigLevel = Optional TrustAll
CacheDir = /var/cache/pacman/pkg
CacheDir = /var/cache/visionlinux/npm

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
